services:
  dns-server:
    container_name: dns-server
    env_file: /mnt/bigSpin/net/Games/LAN-cache/.env
    environment:
      - DNS_SERVER_DOMAIN=dns-server.lan
      - DNS_SERVER_FORWARDERS=10.11.1.1
    hostname: dns-server
    image: technitium/dns-server:latest
    ports:
      - 5380:5380/tcp
      - 53443:53443/tcp
      - 53:53/udp
      - 53:53/tcp
      - 853:853/udp
      - 853:853/tcp
    volumes:
      - config:/etc/dns
  monolithic:
    env_file: /mnt/bigSpin/net/Games/LAN-cache/.env
    image: lancachenet/monolithic:latest
    networks:
      myvlan:
        ipv4_address: 10.11.1.17
        ipv6_address: fd66:1109:2002:1:dade:ceff:fec7:f05c
        mac_address: d8:de:ce:c7:f0:5c
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: unless-stopped
    volumes:
      - /mnt/bigSpin/LAN-cache/cache:/data/cache
      - /mnt/bigSpin/LAN-cache/logs:/data/logs

volumes:
  config:

networks:
  myvlan:
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      config:
        - gateway: 10.11.1.1
          ip_range: 10.11.1.16/29
          subnet: 10.11.1.0/24
        - gateway: fd66:1109:2002:1::1
          ip_range: fd66:1109:2002:1:dade:ceff:fec7:f000/120
          subnet: fd66:1109:2002:1::/64
